### ISSUE TITLE
Not Submitting Multi-Checkbox Form Data

### ISSUE THREAD

**Issue by smcmark** [solepixel/gravityforms-eloqua#3]
I have a form where it employs the check-box type in Gravity.  This lets the user check all that apply.  Whenever multiple boxes are selected, it submits that filed as blank to Eloqua.

**Comment by solepixel** [comment]
@smcmark Would you be willing to share your form configuration and possibly Eloqua access in order to debug this issue?

**Comment by ilovebunny** [comment]
Hi! I was wondering if you have any update on this issue? My client is also having the same problem. Thank you for your help.

**Comment by solepixel** [comment]
Unfortunately I don't have access to an Eloqua account to test/debug this issue. Would you be willing to grant me access in order to fix this issue?

**Comment by ilovebunny** [comment]
Hi there, what kind of access will you need? Just log in to an Eloqua account?

**Comment by solepixel** [comment]
Yeah, especially if you already have a form setup to test the multi-checkbox. You can email it to briandichiara@gmail.com and if you don't mind, also do a Gravity Form Export on the form you're using to make testing/setup a little easier. I should be able to look at it this week and come up with a solution.

**Comment by solepixel** [comment]
@smcmark @ilovebunny Please review the latest version of this plugin to make sure this issue was fixed. I have added support for multi-checkboxes, but would like for you to test to make sure it's working properly. The changes are here:
[gfeloqua.class.php - Line 1073](https://github.com/solepixel/gravityforms-eloqua/blob/master/gravityforms-eloqua/gfeloqua.class.php#L1073)

Be sure your GF Checkbox Values match up with your Eloqua Checkbox values. I'm not sure if it will still save if they don't match, but it's probably best. Let me know if you run into any issues with this.

**Comment by solepixel** [comment]
Closing this ticket due to no replies. If you're having issues with multi-checkbox fields, please re-open with detail about the issue.
