### ISSUE TITLE
Error message: "This add-on needs to be updated. Please contact the developer."

### ISSUE THREAD

**Issue by ryanhellyer** [solepixel/gravityforms-eloqua#5]
This is appearing on the settings page.
"This add-on needs to be updated. Please contact the developer."

Entering credentials doesn't get rid of it, and the credentials don't seem to be working unfortunately. When attempting to edit the Eloqua settings for an individual form, it simply provides a link back to the initial page for entering the Eloqua credentials.

**Comment by solepixel** [comment]
I have found the reason for this error and got it fixed. I'm pushing a new update soon, but waiting to fix one other bug. I need login credentials to Eloqua in order to test everything is working with the API. If you have a working set I can test with, please email me and I can get the new version pushed up. Thanks.

**Comment by rickrussie** [comment]
Having the same issue. All connections to Eloqua are broken at this point.
